const _ = require("lodash");
const getInfoData = ({ fields = [], object = {} }) => {
  return _.pick(object, fields);
};
const removeVietnameseTones = (str) => {
  str = str.replace(
    /[\u00E0\u00E1\u00E2\u1EA1\u1EA3\u1EA5\u1EAF\u00E8\u00E9\u00EA\u1EBB\u1EBD\u1EB9\u00EC\u00ED\u1ECF\u00F2\u00F3\u00F4\u1ECD\u1ED1\u1ED3\u00F9\u00FA\u1EE7\u1EE3\u1ED5\u1ED7\u00F2\u00F3\u00F4\u1EE3\u00F5\u1EEB\u1EF1\u00F5\u1ECD\u00E1\u00E0\u1EB9\u00E3\u0103\u00E9\u00E0\u1EA3\u1EBB\u1EB7\u00E9\u00E8\u1EBD\u1EB9\u00EC\u00ED\u1ECF\u1ECD\u00F3\u00F2\u00F5\u1ECD\u00FA\u00F9\u1EE3\u1EE5\u1EE7\u00FD\u1EF3\u1EF5\u1EF7]/g,
    (char) => {
      const charMap = {
        à: "a",
        á: "a",
        ạ: "a",
        ả: "a",
        ã: "a",
        â: "a",
        ầ: "a",
        ấ: "a",
        ậ: "a",
        ẩ: "a",
        ẫ: "a",
        ă: "a",
        ằ: "a",
        ắ: "a",
        ặ: "a",
        ẳ: "a",
        ẵ: "a",
        è: "e",
        é: "e",
        ẹ: "e",
        ẻ: "e",
        ẽ: "e",
        ê: "e",
        ề: "e",
        ế: "e",
        ệ: "e",
        ể: "e",
        ễ: "e",
        ì: "i",
        í: "i",
        ị: "i",
        ỉ: "i",
        ĩ: "i",
        ò: "o",
        ó: "o",
        ọ: "o",
        ỏ: "o",
        õ: "o",
        ô: "o",
        ồ: "o",
        ố: "o",
        ộ: "o",
        ổ: "o",
        ỗ: "o",
        ơ: "o",
        ờ: "o",
        ớ: "o",
        ợ: "o",
        ở: "o",
        ỡ: "o",
        ù: "u",
        ú: "u",
        ụ: "u",
        ủ: "u",
        ũ: "u",
        ư: "u",
        ừ: "u",
        ứ: "u",
        ự: "u",
        ử: "u",
        ữ: "u",
        ỳ: "y",
        ý: "y",
        ỵ: "y",
        ỷ: "y",
        ỹ: "y",
        đ: "d",
        À: "A",
        Á: "A",
        Ạ: "A",
        Ả: "A",
        Ã: "A",
        Â: "A",
        Ầ: "A",
        Ấ: "A",
        Ậ: "A",
        Ẩ: "A",
        Ẫ: "A",
        Ă: "A",
        Ằ: "A",
        Ắ: "A",
        Ặ: "A",
        Ẳ: "A",
        Ẵ: "A",
        È: "E",
        É: "E",
        Ẹ: "E",
        Ẻ: "E",
        Ẽ: "E",
        Ê: "E",
        Ề: "E",
        Ế: "E",
        Ệ: "E",
        Ể: "E",
        Ễ: "E",
        Ì: "I",
        Í: "I",
        Ị: "I",
        Ỉ: "I",
        Ĩ: "I",
        Ò: "O",
        Ó: "O",
        Ọ: "O",
        Ỏ: "O",
        Õ: "O",
        Ô: "O",
        Ồ: "O",
        Ố: "O",
        Ộ: "O",
        Ổ: "O",
        Ỗ: "O",
        Ơ: "O",
        Ờ: "O",
        Ớ: "O",
        Ợ: "O",
        Ở: "O",
        Ỡ: "O",
        Ù: "U",
        Ú: "U",
        Ụ: "U",
        Ủ: "U",
        Ũ: "U",
        Ư: "U",
        Ừ: "U",
        Ứ: "U",
        Ự: "U",
        Ử: "U",
        Ữ: "U",
        Ỳ: "Y",
        Ý: "Y",
        Ỵ: "Y",
        Ỷ: "Y",
        Ỹ: "Y",
        Đ: "D",
      };
      return charMap[char] || char;
    }
  );

  return str.replace(/[^a-zA-Z0-9 ]/g, ""); // Loại bỏ các ký tự đặc biệt
};

module.exports = {
  getInfoData,
  removeVietnameseTones,
};
